apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Arunk-${ENVIRONMENT}-crm-nginx-log
spec:
  storageClassName: Arunk-${ENVIRONMENT}-crm-nginx-log
  volumeName: Arunk-${ENVIRONMENT}-crm-nginx-log
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
